version: "3.2"

services:

  api:
    build:
      context: .
    image: conduit
    env_file: docker-compose.env
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  # email:
  #   build:
  #     context: .
  #   image: conduit
  #   env_file: docker-compose.env
  #   environment:
  #     SERVICES: email
  #   links:
  #     - redis
  #   depends_on:
  #     - redis

  # users:
  #   build:
  #     context: .
  #   image: conduit
  #   env_file: docker-compose.env
  #   environment:
  #     SERVICES: users
  #   links:
  #     - redis
  #     - mongo
  #   depends_on:
  #     - redis
  #     - mongo

  redis:
    image: redislabs/rejson:latest

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db

  traefik:
    image: traefik:1.7
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml